package model;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 23 14:22:37 EDT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAuditeurCollImpl
  extends EntityCache
{
  /**
   * This is the default constructor (do not remove).
   */
  public PAuditeurCollImpl()
  {
  }
}
