package model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 29 19:10:54 EDT 2010
// ---------------------------------------------------------------------
public interface PAuditeurViewRow
  extends Row
{
  void modifierMotDePasse(String ancienMotDePasse,
                          String nouveauMotDePasse,
                          String confirmationMotDePasse);
}
