package model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 27 09:38:04 EDT 2010
// ---------------------------------------------------------------------
public interface PAuditeurView
  extends ViewObject
{
  boolean connecter(String userName, String password);
}
