package model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 08 14:00:47 EDT 2010
// ---------------------------------------------------------------------
public interface AuditeurViewDevenirJugeRow extends Row
{
    void mettreJuge();

    void limoger();
}
