package model.view.client;

import model.view.common.AuditeurViewDevenirJugeRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 08 14:00:47 EDT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AuditeurViewDevenirJugeRowClient extends RowImpl implements AuditeurViewDevenirJugeRow
{
    /**
     * This is the default constructor (do not remove).
     */
    public AuditeurViewDevenirJugeRowClient()
    {
    }


    public void mettreJuge()
    {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"mettreJuge",null,null);
        return;
    }

    public void limoger()
    {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"limoger",null,null);
        return;
    }
}
