package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 07 16:56:19 EDT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AuditeurViewDevenirJugeImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public AuditeurViewDevenirJugeImpl()
  {
  }
}
