package model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 27 09:38:04 EDT 2010
// ---------------------------------------------------------------------
public interface PAuditeurView
  extends ViewObject
{
    boolean connecter(String userName, String password);

    boolean modifierMotDePasse(String ancienMotDePasse,
                               String nouveauMotDePasse,
                               String confirmationMotDePasse);

    boolean soumettreCandidatureJuge();

    boolean annulerCandidatureJuge();

    String getDateDevenuCandidatJuge();

    String getDateDevenuJuge();

    boolean annulerDemandeJuge();

    boolean editProfile(String nom, String prenom, String rue,
                        String ville, String codePostal, String telephone,
                        String courriel);
}
