package model.view.client;

import model.view.common.AuditeurViewDevenirJuge;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 08 14:20:50 EDT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AuditeurViewDevenirJugeClient extends ViewUsageImpl implements AuditeurViewDevenirJuge
{
    /**
     * This is the default constructor (do not remove).
     */
    public AuditeurViewDevenirJugeClient()
    {
    }

    public void selectionnerAuditeur(String codeAuditeur)
    {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"selectionnerAuditeur",new String [] {"java.lang.String"},new Object[] {codeAuditeur});
        return;
    }

    public void mettreJugePasRow()
    {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"mettreJugePasRow",null,null);
        return;
    }

    public void limogerPasRow()
    {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"limogerPasRow",null,null);
        return;
    }
}
