package model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 08 14:20:50 EDT 2010
// ---------------------------------------------------------------------
public interface AuditeurViewDevenirJuge extends ViewObject
{
    void mettreJugePasRow();

    void limogerPasRow();
}
