package model.view;

import model.view.common.PAuditeurView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 23 14:36:21 EDT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAuditeurViewImpl extends ViewObjectImpl
  implements PAuditeurView
{
    /**
     * This is the default constructor (do not remove).
     */
    public PAuditeurViewImpl()
    {
    }
    
    public boolean connecter(String userName, String password)
    {
      return false;
    }
}