package model.view.client;

import model.view.common.PAuditeurViewRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 29 19:10:54 EDT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAuditeurViewRowClient
  extends RowImpl
  implements PAuditeurViewRow
{
  /**
   * This is the default constructor (do not remove).
   */
  public PAuditeurViewRowClient()
  {
  }

  public void modifierMotDePasse(String ancienMotDePasse,
                                 String nouveauMotDePasse,
                                 String confirmationMotDePasse)
  {
    Object _ret =
      getApplicationModuleProxy().riInvokeExportedMethod(this,"modifierMotDePasse",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {ancienMotDePasse, nouveauMotDePasse, confirmationMotDePasse});
    return;
  }
}
