package model;

import model.view.PAtelierViewImpl;
import model.view.PAuditeurViewImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 30 09:07:26 EDT 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl
{
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl()
    {
    }

    /**
     * Container's getter for PAuditeurView1.
     * @return PAuditeurView1
     */
    public PAuditeurViewImpl getPAuditeurView1()
    {
        return (PAuditeurViewImpl) findViewObject("PAuditeurView1");
    }

    /**
     * Container's getter for PAtelierView1.
     * @return PAtelierView1
     */
    public ViewObjectImpl getPAtelierView1()
    {
        return (ViewObjectImpl) findViewObject("PAtelierView1");
    }

    /**
     * Container's getter for PCategorieView1.
     * @return PCategorieView1
     */
    public ViewObjectImpl getPCategorieView1()
    {
        return (ViewObjectImpl) findViewObject("PCategorieView1");
    }

    /**
     * Container's getter for PCritereView1.
     * @return PCritereView1
     */
    public ViewObjectImpl getPCritereView1()
    {
        return (ViewObjectImpl) findViewObject("PCritereView1");
    }

    /**
     * Container's getter for PEcoleView1.
     * @return PEcoleView1
     */
    public ViewObjectImpl getPEcoleView1()
    {
        return (ViewObjectImpl) findViewObject("PEcoleView1");
    }

    /**
     * Container's getter for PEvaluationView1.
     * @return PEvaluationView1
     */
    public ViewObjectImpl getPEvaluationView1()
    {
        return (ViewObjectImpl) findViewObject("PEvaluationView1");
    }

    /**
     * Container's getter for PExpoView1.
     * @return PExpoView1
     */
    public ViewObjectImpl getPExpoView1()
    {
        return (ViewObjectImpl) findViewObject("PExpoView1");
    }

    /**
     * Container's getter for PExposantView1.
     * @return PExposantView1
     */
    public ViewObjectImpl getPExposantView1()
    {
        return (ViewObjectImpl) findViewObject("PExposantView1");
    }

    /**
     * Container's getter for PExposantArchiveView1.
     * @return PExposantArchiveView1
     */
    public ViewObjectImpl getPExposantArchiveView1()
    {
        return (ViewObjectImpl) findViewObject("PExposantArchiveView1");
    }

    /**
     * Container's getter for PInscriptionView1.
     * @return PInscriptionView1
     */
    public ViewObjectImpl getPInscriptionView1()
    {
        return (ViewObjectImpl) findViewObject("PInscriptionView1");
    }

    /**
     * Container's getter for PInscriptionArchiveView1.
     * @return PInscriptionArchiveView1
     */
    public ViewObjectImpl getPInscriptionArchiveView1()
    {
        return (ViewObjectImpl) findViewObject("PInscriptionArchiveView1");
    }

    /**
     * Container's getter for PLocalView1.
     * @return PLocalView1
     */
    public ViewObjectImpl getPLocalView1()
    {
        return (ViewObjectImpl) findViewObject("PLocalView1");
    }

    /**
     * Container's getter for PRegionView1.
     * @return PRegionView1
     */
    public ViewObjectImpl getPRegionView1()
    {
        return (ViewObjectImpl) findViewObject("PRegionView1");
    }

    /**
     * Container's getter for PSuiviAtelierView1.
     * @return PSuiviAtelierView1
     */
    public ViewObjectImpl getPSuiviAtelierView1()
    {
        return (ViewObjectImpl) findViewObject("PSuiviAtelierView1");
    }

    /**
     * Container's getter for PTypeView1.
     * @return PTypeView1
     */
    public ViewObjectImpl getPTypeView1()
    {
        return (ViewObjectImpl) findViewObject("PTypeView1");
    }

  /**
   * Container's getter for AuditeurViewDevenirJuge1.
   * @return AuditeurViewDevenirJuge1
   */
  public ViewObjectImpl getAuditeurViewDevenirJuge1()
  {
    return (ViewObjectImpl) findViewObject("AuditeurViewDevenirJuge1");
  }
}
